### ISSUE TITLE
Multivariable optimizattion.

### ISSUE THREAD

**Issue by 003Mram** [alpsayin/genetic-algorithm-matlab#3]
How do we perform multivariable optimization?

**Comment by alpsayin** [comment]
DecodeChromosome defines how a genes are converted into an "individual". The return value is an array of your variables.
EvaluateIndividual takes the return value of above and then calculates the "fitness" of the "individual".
The example is already multivariable(=2). It'e defined here:
https://github.com/alpsayin/genetic-algorithm-matlab/blob/439216722c151fd3106dc6cbdb2177c346b69140/FunctionOptimization.m#L21
